services:  
  client:
    build: ./client
    ports:
      - "4200:4200"
    container_name: client
    depends_on: [api, webapi]

  webapi:
    restart: always
    build: ./javaapi
    ports:
      - "9000:9000"
    container_name: webapi
    depends_on: [emartdb]

  api:
    build: ./nodeapi
    ports:
      - "5000:5000"
    container_name: api
    depends_on: [emongo]

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    container_name: nginx
    depends_on: [client, api, webapi]
    command: ['nginx-debug', '-g', 'daemon off;']

  emartdb:
    image: mysql:5.7
    restart: always
    container_name: emartdb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=emartdbpass
      - MYSQL_DATABASE=books

  emongo:
    image: mongo:4
    restart: always
    container_name: emongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATBASE=epoc
